# Generated by Django 3.0b1 on 2020-03-20 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_profile_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='date_of_account_creation',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
