# Generated by Django 3.0b1 on 2020-03-21 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_paytm'),
    ]

    operations = [
        migrations.AddField(
            model_name='paytm',
            name='amount',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
    ]
